name: Lint

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
      - 'poetry.lock'
  pull_request:
    paths:
      - '**.py'
      - 'poetry.lock'

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Powercalc
        uses: actions/checkout@v4
      - uses: ./.github/workflows/uv-composite-action
      - name: Run MyPy
        run: |
          source .venv/bin/activate
          mypy ./custom_components/powercalc
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Powercalc
        uses: actions/checkout@v4
      - uses: ./.github/workflows/uv-composite-action
      - name: Run Ruff
        run: |
          source .venv/bin/activate
          ruff check .
